### PR TITLE
Adding my first file for class

### LINKED ISSUE #8: clawl makes a list
We need to do things!
- [ ] Learn
- [ ] Do
- [ ] Does this work?

### PR DESCRIPTION
**Pull request by clawl**
I created a file!

@githubteacher fixes #8 :smiley:

### CODE REVIEW

**Review by viviant100 — COMMENTED** [review]
Congrats on adding your first file for this class!

**Review by viviant100 — APPROVED** [review]
👍

**Review by viviant100 — CHANGES_REQUESTED** [review]
Any suggestion for restaurants in Maryland?

**Comment by clawl** [comment]
@viviant100 I made some changes, plz approve me

**Review by viviant100 — APPROVED** [review]

**Pull request merged**
